qr/urls.py
from django.urls import path

from . import views

app_name = 'qr'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('link/', views.Links.as_view(), name='link'),
    path('contact/', views.Contacts.as_view(), name='contact'),
    path('contact/upload', views.ContactUpload.as_view(), name='contact_upload'),
    path('location', views.Location.as_view(), name='location'),
    path('location/upload', views.LocationUpload.as_view(), name='location_upload'),
    path('wifi', views.Wifi.as_view(), name='wifi'),
    path('wifi/upload', views.WifiUpload.as_view(), name='wifi_upload')
]

qrDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('old/', include('qrcodes.urls')),
    path('', include('qr.urls'))
]

qrcodes/urls.py
from django.urls import path

from . import views

app_name = 'qrcodes'

urlpatterns = [
    path('', views.index, name='index'),
    path('link/', views.link, name='link'),
    path('contact/', views.contact, name='contact'),
    path('contact/upload', views.contact_upload, name='contact_upload'),
    path('location', views.location, name='location'),
    path('location/upload', views.location_upload, name='location_upload'),
    path('wifi', views.wifi, name='wifi'),
    path('wifi/upload', views.wifi_upload, name='wifi_upload')
]

qrcodes/models.py
from django.db import models

# Create your models here.

qrcodes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotAllowed, HttpResponse, FileResponse
from io import BytesIO
import re

import json

from .services.qr_code_generator import generate_link_qrcode, generate_wifi_qrcode
from .services.vcard_generator import generate_vcard_qrcode, generate_vcard_string, load_data_from_vcard
from .services.location_qr_generator import create_geo_coordinate_qr, create_address_qr, get_geolocation, get_address

# All the routes support GET and POST request. GET renders the view and POST handles form inputs

def index(request):
    # default path redirects to link qr generator
    return redirect('qrcodes:link')

def link(request):
    if request.method == 'GET':
        return render(request, 'qrcodes/link.html')
    elif request.method == 'POST':
        # Get the link
        link_string = request.POST['link']

        qr = generate_link_qrcode(link=link_string)

        # We will have to save image as bytes to stram it back
        image_io = BytesIO()

        qr.save(image_io, format='PNG', quality=70)
        image_io.seek(0)

        # stream image back as a FileResponse
        return FileResponse(image_io, as_attachment=True, filename='qr.png')
    else:
        return HttpResponseNotAllowed(request)

def contact(request):
    if request.method == 'GET':
        # array for displaying variable ammount of phone number fields
        context = {
            'phone_numbers': [1, 2, 3]
        }

        return render(request, 'qrcodes/contact.html', context)
    elif request.method == 'POST':
        # Get the form data
        post_data = request.POST

        # initialize empty phone list to fill it up later on
        phones = []

        # phones have to be an array
        for key in post_data:
            if key.startswith('phone'):
                if post_data.get(key) != '':
                    # extrude the number from the key, that is going to be identifier
                    identifier = re.findall(r'\d+', key)[0]
                    
                    # Add a phone to the list
                    phones.append({
                        'type': post_data.get(f'type{identifier}').upper(),
                        'number': post_data.get(key)
                        })

        # get the data from the form
        firstname = post_data.get('firstname')
        lastname = post_data.get('lastname')
        organisation = post_data.get('organisation')
        job_title = post_data.get('job_title')
        email = post_data.get('email')

        file_type = post_data.get('file')

        if file_type == 'qr':
            qr = generate_vcard_qrcode(firstname=firstname, lastname=lastname, organisation=organisation,
                                        job_title=job_title, phone=phones, email=email)

            image_io = BytesIO()
            
            # save image as byte stream
            qr.save(image_io, format='PNG', quality=70)
            image_io.seek(0)
            
            # send back a file named as firstname_lastname_qr.png
            return FileResponse(image_io, as_attachment=True, filename=f'{firstname}_{lastname}_qr.png')
        elif file_type == 'vcf':
            vcard = generate_vcard_string(firstname=firstname, lastname=lastname, organisation=organisation,
                                            job_title=job_title, phone=phones, email=email)

            # set content type for the browser to expect text based file
            response = HttpResponse(vcard, content_type='text/plain')

            # send back a file named as firstname_lastname.vcf
            response['Content-Disposition'] = f'attachment; filename={firstname}_{lastname}.vcf'

            return response
        # if neither of the options is present just render the contact form
        return render(request, 'qrcodes/contact.html')        
    else:
        return HttpResponseNotAllowed(request)


def contact_upload(request):
    # read the data from .vcf file and display on the form
    if request.method == 'GET':
        return render(request, 'qrcodes/vcard_upload.html')
    elif request.method == 'POST':
        # decode the file as UTF-8
        contact_str = request.FILES['file'].read().decode('UTF-8')

        contact_data = load_data_from_vcard(contact_str)

        context = {
            'contact': contact_data,
            'phone_numbers': range(len(contact_data['phone']), 3)
        }

        return render(request, 'qrcodes/contact.html', context=context)
    else:
        return HttpResponseNotAllowed(request)

def location(request):
    if request.method == 'GET':
        return render(request, 'qrcodes/location.html')
    elif request.method == 'POST':
        post_data = request.POST
        
        if post_data.get('file') == 'qr':
            # chick if address is present
            if post_data.get('address') != '':
                # create a qr based on address
                filename = post_data.get('address')
                qr = create_address_qr(post_data.get('address'))
            else:
                # address is not defined, create qr based on geoloction
                filename = 'location'
                qr = create_geo_coordinate_qr(latitude=post_data.get('latitude'), longitude=post_data.get('longitude'))

            image_io = BytesIO()

            qr.save(image_io, format='PNG', quality=70)
            image_io.seek(0)

            return FileResponse(image_io, as_attachment=True, filename=f'{filename}_qr.png')
        else:
            # check if address is present
            if post_data.get('address') != '':
                address = post_data.get('address')
                filename = post_data.get('address')
                coordinates = get_geolocation(post_data.get('address'))
            else:
                coordinates = {
                    'latitude': post_data.get('latitude'),
                    'longitude': post_data.get('longitude')
                }
                
                filename = 'location'

                # decode the coordinates to get the address
                address = get_address(coordinates['latitude'], coordinates['longitude'])
            
            # put dump everything to json string
            coordinates['address'] = address
            coordinates_str = json.dumps(coordinates)

            # set content type
            response = HttpResponse(coordinates_str, content_type='application/json')
            response['Content-Disposition'] = f'attachment; filename={filename}_config.json'

            return response
    else:
        return HttpResponseNotAllowed(request)

def location_upload(request):
    if request.method == 'GET':
        return render(request, 'qrcodes/location_upload.html')
    elif request.method == 'POST':
        # decode json file and display it on
        location_file = request.FILES['file']

        location_str = location_file.read().decode('UTF-8')

        location_data = json.loads(location_str)

        context = {
            'location': location_data
        }

        return render(request, 'qrcodes/location.html', context=context)
    else:
        return HttpResponseNotAllowed(request)

def wifi(request):
    if request.method == 'GET':
        return render(request, 'qrcodes/wifi.html')
    elif request.method == 'POST':
        post_data = request.POST

        ssid = post_data['ssid']
        password = post_data['password']
        authentication_type = post_data['security']
        hidden = post_data['hidden'] == 'hidden'

        file_type = post_data['file']

        # if required file is a qrcode
        if file_type == 'qr':
            qr = generate_wifi_qrcode(ssid=ssid,
                                        password=password,
                                        authentication_type=authentication_type,
                                        hidden=hidden)

            image_io = BytesIO()

            qr.save(image_io, format='PNG', quality=70)
            image_io.seek(0)

            return FileResponse(image_io, as_attachment=True, filename=f'{ssid}_config_qr.png')
        # if required file is json        
        else:
            wifi_config = {
                'ssid': ssid,
                'password': password,
                'authentication_type': authentication_type,
                'hidden': hidden
            }

            wifi_config_str = json.dumps(wifi_config)

            response = HttpResponse(wifi_config_str, content_type='application/json')
            response['Content-Disposition'] = f'attachment; filename={ssid}_config.json'

            return response
    else:
        return HttpResponseNotAllowed(request)

def wifi_upload(request):
    if request.method == 'GET':
        return render(request, 'qrcodes/wifi_upload.html')
    elif request.method == 'POST':
        # decode json file and display it on the form
        wifi_file = request.FILES['file']

        wifi_str = wifi_file.read().decode('UTF-8')

        wifi_data = json.loads(wifi_str)

        context = {
            'wifi': wifi_data
        }

        return render(request, 'qrcodes/wifi.html', context=context)
    else:
        return HttpResponseNotAllowed(request)

qrcodes/templates/qrcodes/contact.html
{% extends "qrcodes/layout/base.html" %}

{% block title %} Contact - QR {% endblock %}

{% block content %}

<form action="{% url 'qrcodes:contact' %}" method="POST">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="firstname">First name</label>
            <input class="form-control" type="text" id="firstname" name="firstname" placeholder="First" {% if contact %} value="{{ contact.firstname }}" {% endif %}>
        </div>
        <div class="form-group col-md-6">
            <label for="lastname">Last name</label>
            <input class="form-control" type="text" id="lastname" name="lastname" placeholder="Last" {% if contact %} value="{{ contact.lastname }}" {% endif %}>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="organisation">Organisation</label>
            <input class="form-control" type="text" id="organisation" name="organisation" placeholder="Organisation" {% if contact %} value="{{ contact.organization }}" {% endif %}>
        </div>
        <div class="form-group col-md-6">
            <label for="job_title">Title</label>
            <input class="form-control" type="text" id="job_title" name="job_title" placeholder="Title" {% if contact %} value="{{ contact.job_title }}" {% endif %}>
        </div>
    </div>
    {% if not contact %}
        {% for i in phone_numbers %}
        <div class="form-row">
            <div class="form-group col-md-8">
                <label for="phone{{i}}">Phone</label>
                <input class="form-control" type="text" id="phone{{i}}" name="phone{{i}}" placeholder="Phone">
            </div>
            <div class="form-group col-md-4">
                <label for="type{{i}}">Type</label>
                <select class="custom-select" id="type{{i}}" name="type{{i}}">
                    <option value="home">Home</option>
                    <option value="mobile">Mobile</option>
                    <option value="work">Work</option>
                </select>
            </div>
        </div>
        {% endfor %}
    {% else %}
        {% for number in contact.phone %}
        <div class="form-row">
            <div class="form-group col-md-8">
                <label for="phone{{number}}">Phone</label>
                <input class="form-control" type="text" id="phone{{number}}" name="phone{{number}}" placeholder="Phone" value="{{number.number}}">
            </div>
            <div class="form-group col-md-4">
                <label for="type{{number}}">Type</label>
                <select class="custom-select" id="type{{number}}" name="type{{number}}">
                    <option value="{{ number.type }}">{{number.type}}</option>
                    <option value="home">Home</option>
                    <option value="mobile">Mobile</option>
                    <option value="work">Work</option>
                </select>
            </div>
        </div>
        {% endfor %}
        {% if contact.phone|length < 3 %}
            {% for number in phone_numbers %}
            <div class="form-row">
                <div class="form-group col-md-8">
                    <label for="phone{{number}}">Phone</label>
                    <input class="form-control" type="text" id="phone{{number}}" name="phone{{number}}" placeholder="Phone">
                </div>
                <div class="form-group col-md-4">
                    <label for="type{{number}}">Type</label>
                    <select class="custom-select" id="type{{number}}" name="type{{number}}">
                        <option value="home">Home</option>
                        <option value="mobile">Mobile</option>
                        <option value="work">Work</option>
                    </select>
                </div>
            </div>
            {% endfor %}
        {% endif %}
    {% endif %}
    <div class="form-group">
        <label for="email">E-Mail</label>
        <input class="form-control" type="email" id="email" name="email" placeholder="E-Mail" {% if contact %} value="{{ contact.email }}" {% endif %}>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="file" id="qrcode" value="qr" checked>
        <label class="form-check-label" for="qrcode">
            Download QR code
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="file" id="vcf" value="vcf">
        <label class="form-check-label" for="vcf">
            Download VCF file
        </label>
    </div>
    <button type="submit" class="btn btn-success">Generate</button>
    {% if not contact %}
        <a class="btn btn-primary" href="{% url 'qrcodes:contact_upload' %}">Upload VCF</a>
    {% endif %}
</form>
{% endblock %}

qrcodes/templates/qrcodes/link.html
{% extends "qrcodes/layout/base.html" %}

{% block title %} Link - QR {% endblock %}

{% block content %}
<form action="{% url 'qrcodes:link' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="link">Link</label>
        <input class="form-control" type="text" id="link" name="link" placeholder="www.google.com">
    </div>
    <button type="submit" class="btn btn-success">Generate QR</button>
</form>
{% endblock %}

qrcodes/templates/qrcodes/location.html
{% extends "qrcodes/layout/base.html" %}

{% block title %} Location - QR {% endblock %}

{% block content %}
<form action="{% url 'qrcodes:location' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="address">Address</label>
        <input class="form-control" type="text" id="address" name="address" {% if location %} value="{{location.address}}" {% endif %}>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="latitude">Latitude</label>
            <input class="form-control" type="text" id="latitude" name="latitude" placeholder="latitude" {% if location %} value="{{location.latitude }}" {% endif %}>
        </div>
        <div class="form-group col-md-6">
            <label for="longitude">Longitude</label>
            <input class="form-control" type="text" id="longitude" name="longitude" placeholder="longitude" {% if location %} value="{{location.longitude }}" {% endif %}>
        </div>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="file" id="qrcode" value="qr" checked>
        <label class="form-check-label" for="qrcode">
            Download QR code
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="file" id="json" value="json">
        <label class="form-check-label" for="json">
            Download JSON file
        </label>
    </div>
    <button type="submit" class="btn btn-success">Generate</button>
    <a class="btn btn-primary" href="{% url 'qrcodes:location_upload' %}">Upload JSON</a>
</form>
{% endblock %}

qrcodes/templates/qrcodes/location_upload.html
{% extends "qrcodes/layout/base.html" %}

{% block title %} Location - upload {% endblock %}

{% block content %}
<form action="{% url 'qrcodes:location_upload' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}    
    <div class="custom-file">
        <input type="file" class="custom-file-input" id="file" name="file" required>
        <label class="custom-file-label" for="file">Choose a .json file</label>
    </div>
    <button type="submit" class="btn btn-success">Upload</button>
</form>
{% endblock %}

qrcodes/templates/qrcodes/vcard_upload.html
{% extends "qrcodes/layout/base.html" %}

{% block title %} VCard - upload {% endblock %}

{% block content %}
<form action="{% url 'qrcodes:contact_upload' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}    
    <div class="custom-file">
        <input type="file" class="custom-file-input" id="file" name="file" required>
        <label class="custom-file-label" for="file">Choose a .vcf file</label>
    </div>
    <button type="submit" class="btn btn-success">Upload</button>
</form>
{% endblock %}

qrcodes/templates/qrcodes/wifi.html
{% extends "qrcodes/layout/base.html" %}

{% block title %} Wifi - QR {% endblock %}

{% block content %}
<form action="{% url 'qrcodes:wifi' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="ssid">SSID</label>
        <input class="form-control" type="text" id="ssid" name="ssid" placeholder="SSID" {% if wifi %} value="{{wifi.ssid }}" {% endif%}>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input class="form-control" type="text" id="password" name="password" placeholder="password" {% if wifi %} value="{{wifi.password }}" {% endif %}>
    </div>
    <div class="form-group">
        <label for="security">Security</label>
        <select class="custom-select" id="security" name="security">
            <option value="nopass" {% if wifi %} {% if wifi.security == 'nopass' %} selected {% endif %} {% endif %}>None</option>
            <option value="WEP" {% if wifi %} {% if wifi.security == 'WEP' %} selected {% endif %} {% endif %}>WEP</option>
            <option value="WPA" {% if wifi %} {% if wifi.security == 'WPA' %} selected {% endif %} {% endif %}>WPA</option>
        </select>
    </div>
    <div class="form-group">
        <label for="hidden">Hidden</label>
        <select class="custom-select" id="hidden" name="hidden">
            <option value="visible" {% if wifi %} {% if not wifi.hidden %} selected {% endif %} {% endif%}>No</option>
            <option value="hidden" {% if wifi %} {% if wifi.hidden %} selected {% endif %} {% endif%} >Yes</option>
        </select>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="file" id="qrcode" value="qr" checked>
        <label class="form-check-label" for="qrcode">
            Download QR code
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="file" id="json" value="json">
        <label class="form-check-label" for="json">
            Download JSON file
        </label>
    </div>
    <button type="submit" class="btn btn-success">Generate</button>
    <a class="btn btn-success" href="{% url 'qrcodes:wifi_upload' %}">Upload JSON</a>
</form>
{% endblock %}

qrcodes/templates/qrcodes/wifi_upload.html
{% extends "qrcodes/layout/base.html" %}

{% block title %} Wifi - upload {% endblock %}

{% block content %}
<form action="{% url 'qrcodes:wifi_upload' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}    
    <div class="custom-file">
        <input type="file" class="custom-file-input" id="file" name="file" required>
        <label class="custom-file-label" for="file">Choose a .json file</label>
    </div>
    <button type="submit" class="btn btn-success">Upload</button>
</form>
{% endblock %}